### ISSUE TITLE
ofver bug when installation fails

### ISSUE THREAD

**Issue by CarlosBermudo** [fp7-ofelia/ocf#12] opened 2012-08-03 12:16 UTC
ofver install does not delete .ofverLock when installation fails.

**Comment by msune** [comment] 2012-08-03 14:58
This might not a bug in ofver I guess, but an improper handling of errors in the scripts under /bin/versions/. All the calls that inherntly have to exit when failing must use error call defined in:

http://code.google.com/p/ofver/source/browse/ofver/common/utils

Please check that command is called like this myCommandThatCanFail || error "My error msg". 

Also add the affected component/s to the issue please, and a further description on where installation fails, so that we can track problem.

**Comment by CarolinaFernandez** [comment] 2012-08-06 12:10
This problem is apparently due to a previous movement to another folder, making it impossible to remove the lock file.

When the "unlock" function in the "utils" file is modified to point to the "execution path", then the lock file is removed after the errors. This has been successfully solved and tested for a database error during the installation of the "Expedient" plugin -- the other plugins point to this installation file, then the same error should occur for them.

**Comment by lbergesio** [comment] 2012-08-07 19:17
As Marc said this is for sure due to some custom script which is not using the error function or it is entering some directory and not going back to the previous dir (normally this is done by saving TMP_DIR = PWD at the beginning of the script and restoring it by doing cd TMP_DIR at the end). Since it was tested in the installation of v0.21.1 then it must be in some custom script for this version. Nevertheless I personally do not see a problem in modifying the unlock functiok to use the global var EXCEC_PATH and assure it will reach the lock file.

**Comment by CarolinaFernandez** [comment] 2012-08-20 11:53
Changes have been committed to the ofver's Google code project and could be propagated to OCF for the v0.3 milestone.
Closing issue.

**Closed as completed by CarolinaFernandez** 2012-08-20 11:53 UTC
Labels: bug
