### ISSUE TITLE
VM naming conflicts

### ISSUE THREAD

**Issue by vkotronis** [fp7-ofelia/ocf#90] opened 2012-11-29 20:59 UTC
There is the probability of naming conflicts when VT manager tries to start two VMs with the same name. For example, if two users in different slices choose the same VM server of an island to create two VMs with the exact same name (e.g. "controller"), one of the two VMs will not be able to start when the other one is alreadty running. In fact, there is no exception thrown at the Expedient's level (just the conflicting VM takes forever to start), and the XEN server (oxad) log reports naming collisions and inability to start the VM. Shoudn't the user-defined VM names be sanitized before reaching the agent to avoid conflicts?

p.s. If this is a double-ticket please ignore it.

**Comment by CarolinaFernandez** [comment] 2012-12-05 10:34
We have (presumably) identified the cause of the problem and the fix will be released in 0.3.1.
Before closing this issue for good we'll make a brief explanation of the problem and its solution.

Thanks for reporting this issue, by the way.

**Closed as completed** 2012-12-07 09:05 UTC
Labels: bug, VMManager, Expedient, agent, CRITICAL

**Comment by CarolinaFernandez** [comment] 2012-12-10 18:34
Explanation for issue: a mutex deadlock happened.

The method `startDomain` checked for an alias in case another VM with the same name was already running. This method (`__findAliasForDuplicatedVmName`) acquired a mutex in the first place, then called another method (`__getConnection`) who tried to acquire the previous lock -- not yet to be released. Therefore the deadlock.

The solution was to remove the mutex inside `__findAliasForDuplicatedVmName`, since there was one already being asked in the connection establishment.

**Previous version: `vt_manager/src/python/agent/xen/XendManager.py`**

> ```
>    def __findAliasForDuplicatedVmName(vm):
>             with XendManager._mutex:
>                     #Duplicated VM name; find new temporal alias
>                     newVmName = vm.name
>                     for i in range(OXA_XEN_MAX_DUPLICATED_NAME_VMS):
>                             if not XendManager.isVmRunning(vm.name+"_"+str(i)):
>                                     return str(vm.name+"_"+str(i))
>                     Exception("Could not generate an alias for a duplicated vm name.")
> ```

**New version: `vt_manager/src/python/agent/xen/XendManager.py`**

> ```
>    def __findAliasForDuplicatedVmName(vm):
>             #Duplicated VM name; find new temporal alias
>             newVmName = vm.name
>             for i in range(OXA_XEN_MAX_DUPLICATED_NAME_VMS):
>                     if not XendManager.isVmRunning(vm.name+"_"+str(i)):
>                             return str(vm.name+"_"+str(i))
>             Exception("Could not generate an alias for a duplicated vm name.")
> ```
